-- ===================================================================
-- V10: Modelagem Relacional Normalizada do Marketplace Clyvo Vet (3FN)
-- Resolve formalmente a arquitetura Two-Sided Marketplace com:
-- 1. Expansão de T_CLINICA (CNPJ, Razão Social, CRMV, Chave Pix, Split)
-- 2. T_SERVICO (Catálogo de serviços preventivos ofertados pelas clínicas)
-- 3. T_AGENDAMENTO (Reserva de atendimento entre Tutor, Pet, Clínica e Serviço)
-- 4. T_TRANSACAO (Registro financeiro in-app retido pelo gateway)
-- 5. T_COMISSAO (Livro-razão contábil do split com custódia/escrow)
-- ===================================================================

-- 1. Expansão da Tabela de Clínicas Parceiras
ALTER TABLE T_CLINICA ADD cnpj VARCHAR(18);
ALTER TABLE T_CLINICA ADD razao_social VARCHAR(150);
ALTER TABLE T_CLINICA ADD crmv_responsavel VARCHAR(30);
ALTER TABLE T_CLINICA ADD email VARCHAR(100);
ALTER TABLE T_CLINICA ADD chave_pix_repasse VARCHAR(100);
ALTER TABLE T_CLINICA ADD taxa_comissao_customizada NUMERIC(5,2) DEFAULT 15.00 NOT NULL;
ALTER TABLE T_CLINICA ADD ativo BOOLEAN DEFAULT TRUE NOT NULL;

-- Atualização cadastral das clínicas existentes do seed
UPDATE T_CLINICA SET 
    cnpj = '12.345.678/0001-90',
    razao_social = 'Hospital Veterinário Clyvo Central Ltda',
    crmv_responsavel = 'CRMV-SP 45.890',
    email = 'contato@clyvocentral.com.br',
    chave_pix_repasse = 'financeiro@clyvocentral.com.br'
WHERE id = 1;

UPDATE T_CLINICA SET 
    cnpj = '98.765.432/0001-10',
    razao_social = 'Clínica Preventiva Pet Care Jardins Eireli',
    crmv_responsavel = 'CRMV-SP 32.110',
    email = 'jardins@petcare.com.br',
    chave_pix_repasse = 'repasse@petcare.com.br'
WHERE id = 2;

-- 2. Tabela de Catálogo de Serviços das Clínicas Credenciadas
CREATE TABLE T_SERVICO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    preco_base NUMERIC(10,2) NOT NULL,
    duracao_minutos INT DEFAULT 45 NOT NULL,
    permite_desconto_fidelidade BOOLEAN DEFAULT TRUE NOT NULL,
    ativo BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT fk_servico_clinica FOREIGN KEY (clinica_id) REFERENCES T_CLINICA(id)
);
CREATE INDEX idx_servico_clinica ON T_SERVICO(clinica_id);

-- 3. Tabela de Agendamentos (Contrato de Intermediação de Consulta)
CREATE TABLE T_AGENDAMENTO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    tutor_cpf VARCHAR(14) NOT NULL,
    clinica_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    data_hora_agendamento TIMESTAMP NOT NULL,
    status_agendamento VARCHAR(30) DEFAULT 'SOLICITADO' NOT NULL,
    observacoes VARCHAR(500),
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_agend_pet FOREIGN KEY (pet_id) REFERENCES T_PET(id) ON DELETE CASCADE,
    CONSTRAINT fk_agend_tutor FOREIGN KEY (tutor_cpf) REFERENCES T_TUTOR(cpf),
    CONSTRAINT fk_agend_clinica FOREIGN KEY (clinica_id) REFERENCES T_CLINICA(id),
    CONSTRAINT fk_agend_servico FOREIGN KEY (servico_id) REFERENCES T_SERVICO(id)
);
CREATE INDEX idx_agend_pet ON T_AGENDAMENTO(pet_id);
CREATE INDEX idx_agend_tutor ON T_AGENDAMENTO(tutor_cpf);
CREATE INDEX idx_agend_clinica ON T_AGENDAMENTO(clinica_id);

-- 4. Tabela de Transações Financeiras (Captura In-App & Gateway)
CREATE TABLE T_TRANSACAO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id BIGINT NOT NULL UNIQUE,
    codigo_transacao_gateway VARCHAR(100) NOT NULL UNIQUE,
    metodo_pagamento VARCHAR(30) NOT NULL,
    status_transacao VARCHAR(30) DEFAULT 'PENDENTE' NOT NULL,
    valor_bruto NUMERIC(10,2) NOT NULL,
    valor_desconto_fidelidade NUMERIC(10,2) DEFAULT 0.00 NOT NULL,
    valor_liquido_pago NUMERIC(10,2) NOT NULL,
    codigo_voucher VARCHAR(50) NOT NULL UNIQUE,
    qr_code_hash VARCHAR(255) NOT NULL,
    voucher_utilizado BOOLEAN DEFAULT FALSE NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    data_pagamento TIMESTAMP,
    data_utilizacao_voucher TIMESTAMP,
    CONSTRAINT fk_transacao_agendamento FOREIGN KEY (agendamento_id) REFERENCES T_AGENDAMENTO(id) ON DELETE CASCADE
);
CREATE INDEX idx_transacao_voucher ON T_TRANSACAO(codigo_voucher);

-- 5. Tabela de Comissões e Split Financeiro (Ledger do Marketplace com Escrow)
CREATE TABLE T_COMISSAO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transacao_id BIGINT NOT NULL UNIQUE,
    clinica_id BIGINT NOT NULL,
    percentual_take_rate NUMERIC(5,2) DEFAULT 15.00 NOT NULL,
    valor_comissao_plataforma NUMERIC(10,2) NOT NULL,
    valor_repasse_clinica NUMERIC(10,2) NOT NULL,
    status_repasse VARCHAR(35) DEFAULT 'RETIDO_ESCROW' NOT NULL,
    data_previsao_repasse DATE NOT NULL,
    data_liquidacao_repasse TIMESTAMP,
    CONSTRAINT fk_comissao_transacao FOREIGN KEY (transacao_id) REFERENCES T_TRANSACAO(id) ON DELETE CASCADE,
    CONSTRAINT fk_comissao_clinica FOREIGN KEY (clinica_id) REFERENCES T_CLINICA(id)
);
CREATE INDEX idx_comissao_clinica ON T_COMISSAO(clinica_id);
CREATE INDEX idx_comissao_status ON T_COMISSAO(status_repasse);

-- ===================================================================
-- Seed de Dados do Marketplace: Catálogo de Serviços das Clínicas
-- ===================================================================

-- Serviços do Hospital Veterinário Clyvo Central (ID 1)
INSERT INTO T_SERVICO (clinica_id, nome, descricao, categoria, preco_base, duracao_minutos, permite_desconto_fidelidade, ativo) VALUES
(1, 'Consulta Preventiva de Longevidade', 'Avaliação clínica integral, histórico de check-ins e triagem com escore preventivo de longevidade.', 'CONSULTA_PREVENTIVA', 180.00, 45, TRUE, TRUE),
(1, 'Check-up Geriátrico & Painel Sanguíneo', 'Hemograma completo, perfil renal/hepático, eletrólitos e dosagem de biomarcadores para pets seniores.', 'CHECKUP_GERIATRICO', 350.00, 60, TRUE, TRUE),
(1, 'Profilaxia Dentária Preventiva', 'Remoção ultrassônica de cálculo dentário com polimento e avaliação gengival para prevenção bacteriana sistêmica.', 'PROFILAXIA_DENTAL', 420.00, 90, TRUE, TRUE),
(1, 'Vacinação Polivalente V10 / Antirrábica', 'Imunização preventiva anual com vacinas importadas e reforço de proteção viral e bacteriana.', 'VACINACAO_ANUAL', 130.00, 30, TRUE, TRUE);

-- Serviços da Clínica Preventiva Pet Care Jardins (ID 2)
INSERT INTO T_SERVICO (clinica_id, nome, descricao, categoria, preco_base, duracao_minutos, permite_desconto_fidelidade, ativo) VALUES
(2, 'Consulta Preventiva Felina / Silvestres', 'Atendimento especializado Cat Friendly e de Animais Exóticos/Silvestres em ambiente com isolamento acústico.', 'CONSULTA_PREVENTIVA', 200.00, 50, TRUE, TRUE),
(2, 'Ultrassonografia Abdominal Preventiva', 'Mapeamento abdominal preventivo com Doppler color para detecção precoce de nódulos e nefropatias.', 'EXAMES_LABORATORIAIS', 280.00, 45, TRUE, TRUE);

-- ===================================================================
-- Seed de Agendamento, Transação e Split em Custódia
-- ===================================================================

-- Agendamento de Consulta de Longevidade para o pet Thor (ID 1), Tutor Gabriel Maciel
INSERT INTO T_AGENDAMENTO (pet_id, tutor_cpf, clinica_id, servico_id, data_hora_agendamento, status_agendamento, observacoes, data_criacao) VALUES
(1, '123.456.789-00', 1, 1, CURRENT_TIMESTAMP + INTERVAL '2' DAY, 'CONFIRMADO', 'Agendamento preventivo semestral com desconto nível PRATA (10%).', CURRENT_TIMESTAMP - INTERVAL '1' HOUR);

-- Transação In-App correspondente (R$ 180,00 - 10% desconto = R$ 162,00 pago via PIX)
INSERT INTO T_TRANSACAO (agendamento_id, codigo_transacao_gateway, metodo_pagamento, status_transacao, valor_bruto, valor_desconto_fidelidade, valor_liquido_pago, codigo_voucher, qr_code_hash, voucher_utilizado, data_criacao, data_pagamento) VALUES
(1, 'PAY-GW-SEED-2026-001', 'PIX', 'PAGO', 180.00, 18.00, 162.00, 'CLYVO-MKT-THOR92', 'QR-CLYVO-SEED-PET1-HASH92', FALSE, CURRENT_TIMESTAMP - INTERVAL '1' HOUR, CURRENT_TIMESTAMP - INTERVAL '55' MINUTE);

-- Comissão e Split Contábil (15% de take-rate sobre R$ 162,00 = R$ 24,30 Clyvo; R$ 137,70 Clínica em Escrow)
INSERT INTO T_COMISSAO (transacao_id, clinica_id, percentual_take_rate, valor_comissao_plataforma, valor_repasse_clinica, status_repasse, data_previsao_repasse) VALUES
(1, 1, 15.00, 24.30, 137.70, 'RETIDO_ESCROW', CURRENT_DATE + 3);
