-- ===================================================================
-- V1: Criação das Tabelas Base do Sistema Clyvo Vet
-- ===================================================================

-- 1. Tabela de Usuários (Autenticação Spring Security)
CREATE TABLE T_USUARIO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL, -- ROLE_ADMIN, ROLE_TUTOR
    nome_completo VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

-- 2. Tabela de Raças de Animais
CREATE TABLE T_RACA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    especie VARCHAR(20) NOT NULL DEFAULT 'CANINA', -- CANINA, FELINA
    propensao_doenca VARCHAR(255),
    expectativa_vida INT NOT NULL,
    cuidados_especiais VARCHAR(500)
);

-- 3. Tabela de Tutores
CREATE TABLE T_TUTOR (
    cpf VARCHAR(14) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(100),
    usuario_id BIGINT UNIQUE,
    CONSTRAINT fk_tutor_usuario FOREIGN KEY (usuario_id) REFERENCES T_USUARIO(id)
);

-- 4. Tabela de Clínicas Veterinárias
CREATE TABLE T_CLINICA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cnpj VARCHAR(150) NOT NULL,
    telefone VARCHAR(20),
    cidade VARCHAR(100) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    atendimento_24h BOOLEAN DEFAULT FALSE
);

-- 5. Tabela de Pets (Animais de Estimação)
CREATE TABLE T_PET (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    peso NUMERIC(5,2) NOT NULL,
    status_longevidade VARCHAR(500) DEFAULT 'Avaliação preventiva pendente',
    escore_saude INT DEFAULT 85,
    raca_id BIGINT NOT NULL,
    tutor_cpf VARCHAR(14) NOT NULL,
    CONSTRAINT fk_pet_raca FOREIGN KEY (raca_id) REFERENCES T_RACA(id),
    CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_cpf) REFERENCES T_TUTOR(cpf)
);
