-- ===================================================================
-- V2: Criação das Tabelas dos Fluxos Clínicos e Gamificação (Clyvo Vet)
-- Fluxo 1: Check-in Diário de Cuidado, Streaks, Badges e Recompensas
-- Fluxo 2: Triagem Preventiva com Escore de Longevidade & Insights de IA
-- ===================================================================

-- 1. Tabela de Recompensas e Gamificação do Tutor
CREATE TABLE T_RECOMPENSA_TUTOR (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_cpf VARCHAR(14) NOT NULL UNIQUE,
    pontos_acumulados INT DEFAULT 0,
    streak_dias INT DEFAULT 0,
    ultimo_checkin DATE,
    desconto_percentual INT DEFAULT 0, -- Desconto acumulado para consultas
    nivel_fidelidade VARCHAR(30) DEFAULT 'BRONZE', -- BRONZE, PRATA, OURO, DIAMANTE
    CONSTRAINT fk_recompensa_tutor FOREIGN KEY (tutor_cpf) REFERENCES T_TUTOR(cpf)
);

-- 2. Tabela de Check-ins Diários do Pet (Linha do Tempo de Cuidado)
CREATE TABLE T_CHECKIN_DIARIO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    data_checkin DATE NOT NULL,
    alimentacao_status VARCHAR(30) NOT NULL, -- RECOMENDADA, PETISCOS_MODERADOS, EXCESSO, POUCO_APETITE
    remedio_administrado BOOLEAN DEFAULT FALSE,
    minutos_atividade INT DEFAULT 0,
    humor_pet VARCHAR(30) NOT NULL, -- ENERGICO, TRANQUILO, APATICO, COCEIRA_DESCONFORTO, DOR
    sintomas_observados VARCHAR(500),
    pontos_ganhos INT DEFAULT 10,
    alerta_gerado BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_checkin_pet FOREIGN KEY (pet_id) REFERENCES T_PET(id)
);

-- 3. Tabela de Badges e Conquistas de Longevidade
CREATE TABLE T_BADGE_CONQUISTA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    codigo_badge VARCHAR(50) NOT NULL,
    nome_badge VARCHAR(100) NOT NULL,
    icone VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_conquista DATE NOT NULL,
    CONSTRAINT fk_badge_pet FOREIGN KEY (pet_id) REFERENCES T_PET(id)
);

-- 4. Tabela de Consultas e Triagem Preventiva de Longevidade (Fluxo 2)
CREATE TABLE T_CONSULTA_TRIAGEM (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    data_solicitacao TIMESTAMP NOT NULL,
    data_consulta TIMESTAMP,
    status VARCHAR(30) NOT NULL, -- SOLICITADA, AGENDADA, CONCLUIDA, CANCELADA
    queixa_principal VARCHAR(500) NOT NULL,
    peso_aferido NUMERIC(5,2),
    temperatura NUMERIC(4,1),
    frequencia_cardiaca INT,
    escore_longevidade INT, -- 0 a 100
    classificacao_risco VARCHAR(20), -- BAIXO, MODERADO, ALTO
    insight_ia VARCHAR(1000), -- Insights preditivos da IA sobre raça + checkins
    parecer_veterinario VARCHAR(1000),
    veterinario_id BIGINT,
    CONSTRAINT fk_triagem_pet FOREIGN KEY (pet_id) REFERENCES T_PET(id),
    CONSTRAINT fk_triagem_vet FOREIGN KEY (veterinario_id) REFERENCES T_USUARIO(id)
);

-- 5. Tabela de Linha do Tempo / Prontuário Clínico Consolidado
CREATE TABLE T_HISTORICO_CLINICO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    data_registro TIMESTAMP NOT NULL,
    tipo_evento VARCHAR(50) NOT NULL, -- CHECKIN_DIARIO, TRIAGEM_PREVENTIVA, VACINACAO, ALERTA_SAUDE
    descricao VARCHAR(500) NOT NULL,
    conduta_adotada VARCHAR(1000),
    CONSTRAINT fk_historico_pet FOREIGN KEY (pet_id) REFERENCES T_PET(id)
);

-- Índices de Performance
CREATE INDEX idx_pet_tutor ON T_PET(tutor_cpf);
CREATE INDEX idx_checkin_pet_data ON T_CHECKIN_DIARIO(pet_id, data_checkin);
CREATE INDEX idx_triagem_pet ON T_CONSULTA_TRIAGEM(pet_id);
