-- ===================================================================
-- V4: Login social (Google) e recuperação de senha por e-mail
-- ===================================================================
-- Contexto: até aqui só existia autenticação local (usuário/senha) via
-- T_USUARIO. Esta migração:
--   1) Permite senha nula (contas criadas via Google não têm senha local);
--   2) Registra a origem da conta (LOCAL ou GOOGLE) e o ID do provedor;
--   3) Torna o e-mail único, pois é a chave usada para casar uma conta
--      local existente com o login social e para a recuperação de senha;
--   4) Cria a tabela de tokens de recuperação de senha (um token por
--      solicitação, com validade e uso únicos).
-- ===================================================================

ALTER TABLE T_USUARIO ALTER COLUMN password SET NULL;

ALTER TABLE T_USUARIO ADD COLUMN provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE T_USUARIO ADD COLUMN provider_id VARCHAR(100);
ALTER TABLE T_USUARIO ADD COLUMN avatar_url VARCHAR(500);

ALTER TABLE T_USUARIO ADD CONSTRAINT uk_usuario_email UNIQUE (email);
ALTER TABLE T_USUARIO ADD CONSTRAINT uk_usuario_provider_id UNIQUE (provider_id);

COMMENT ON COLUMN T_USUARIO.provider IS 'Origem da conta: LOCAL (usuário/senha) ou GOOGLE (login social).';
COMMENT ON COLUMN T_USUARIO.provider_id IS 'Identificador único do usuário no provedor externo (ex.: "sub" do Google). Nulo para contas LOCAL.';
COMMENT ON COLUMN T_USUARIO.avatar_url IS 'URL da foto de perfil obtida do provedor social, exibida na sidebar.';

CREATE TABLE T_TOKEN_RECUPERACAO_SENHA (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    token VARCHAR(100) NOT NULL UNIQUE,
    data_criacao TIMESTAMP NOT NULL,
    data_expiracao TIMESTAMP NOT NULL,
    usado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_token_usuario FOREIGN KEY (usuario_id) REFERENCES T_USUARIO(id)
);

COMMENT ON TABLE T_TOKEN_RECUPERACAO_SENHA IS 'Tokens de uso único para redefinição de senha, enviados por e-mail e válidos por tempo limitado.';
COMMENT ON COLUMN T_TOKEN_RECUPERACAO_SENHA.token IS 'Valor aleatório (UUID) enviado por e-mail no link de redefinição.';
COMMENT ON COLUMN T_TOKEN_RECUPERACAO_SENHA.usado IS 'Impede que o mesmo link de redefinição seja utilizado mais de uma vez.';

CREATE INDEX idx_token_recuperacao_token ON T_TOKEN_RECUPERACAO_SENHA(token);
