-- ===================================================================
-- V6: Módulo de Checkout In-App, Split de Pagamento e Voucher Digital
-- Evita a fuga de plataforma (Platform Leakage) garantindo a retenção
-- do take-rate no gateway antes do repasse líquido à clínica parceira.
-- ===================================================================

CREATE TABLE T_AGENDAMENTO_SERVICO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL,
    tutor_cpf VARCHAR(14) NOT NULL,
    tipo_servico VARCHAR(50) NOT NULL,
    descricao_servico VARCHAR(255) NOT NULL,
    valor_original NUMERIC(10,2) NOT NULL,
    desconto_fidelidade NUMERIC(10,2) DEFAULT 0.00 NOT NULL,
    valor_final NUMERIC(10,2) NOT NULL,
    taxa_clyvo_percentual NUMERIC(5,2) DEFAULT 15.00 NOT NULL,
    valor_comissao_clyvo NUMERIC(10,2) NOT NULL,
    valor_repasse_clinica NUMERIC(10,2) NOT NULL,
    status_pagamento VARCHAR(30) NOT NULL,
    metodo_pagamento VARCHAR(30) NOT NULL,
    codigo_voucher VARCHAR(50) NOT NULL UNIQUE,
    qr_code_hash VARCHAR(255) NOT NULL,
    clinica_parceira VARCHAR(150) DEFAULT 'Hospital Veterinário Central Parceiro Clyvo' NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    data_pagamento TIMESTAMP,
    data_utilizacao TIMESTAMP,
    observacoes VARCHAR(500),
    CONSTRAINT fk_agendamento_pet FOREIGN KEY (pet_id) REFERENCES T_PET(id),
    CONSTRAINT fk_agendamento_tutor FOREIGN KEY (tutor_cpf) REFERENCES T_TUTOR(cpf)
);

CREATE INDEX idx_agendamento_tutor ON T_AGENDAMENTO_SERVICO(tutor_cpf);
CREATE INDEX idx_agendamento_pet ON T_AGENDAMENTO_SERVICO(pet_id);
CREATE INDEX idx_agendamento_voucher ON T_AGENDAMENTO_SERVICO(codigo_voucher);
